services:
    _defaults:
        autoconfigure: true
        autowire: true

    app.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            -
                - '@serializer.denormalizer.array'
                - '@serializer.normalizer.datetime'
                - '@serializer.normalizer.backed_enum'
                - '@serializer.normalizer.problem'
                - '@daybreak_studios_rest.serializer.normalizer.object'
                - '@daybreak_studios_rest.serializer.denormalizer.entity'
            -
                - '@serializer.encoder.json'
                - '@serializer.encoder.csv'
                - '@serializer.encoder.xml'
                - '@serializer.encoder.yaml'
