daybreak_studios_rest:
    serializer: 'app.serializer'
    validator: 'validator'
    crud:
        enabled: true
        entities:
            - '%kernel.project_dir%/src/Entity'

        use_localized_routes: true