imports:
    -
        resource: './services'
        type: 'directory'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller'

    App\Command\:
        resource: '../src/Command'

    App\Api\Transformers\:
        resource: '../src/Api/Transformers'

    App\DataFixtures\:
        resource: '../src/DataFixtures'

    App\Import\Importers\:
        resource: '../src/Import/Importers'

    App\Response\Listeners\:
        resource: '../src/Response/Listeners'

    daybreak_studios_rest.query_manager:
        class: DaybreakStudios\DoctrineQueryDocument\QueryManager
        bind:
            $objectManager: '@Doctrine\ORM\EntityManagerInterface'
        calls:
            - ['setDiscriminatorResolverFunctionName', ['TYPE']]

    DaybreakStudios\DoctrineQueryDocument\QueryManagerInterface: '@daybreak_studios_rest.query_manager'
